### ISSUE TITLE
Error pane appearing and shifting lines up

### ISSUE THREAD

**Issue by benswinburne** [kylef/apiblueprint.vim#12]
I'm having some problems whereby Syntastic (presumably) pops up upon save but only in `apib` files. It doesn't do it when saving PHP or HTML files (the other types I check with Syntastic).

![image](https://cloud.githubusercontent.com/assets/1208977/13782902/f6767a30-eac0-11e5-87c9-b51bf7853d9f.png)

As you can probably see from the image above, it doesn't seem to render properly. The content in the editor pane is shifted up by the number of lines in the error list, but then I scroll to make the errors disappear and vim puts the lines back in the right place one by one. It then leaves visual artefacts in the gutter which i can't clear unless i scroll them off the screen.

![image](https://cloud.githubusercontent.com/assets/1208977/13783166/251097d0-eac2-11e5-9d06-2ff7c0a97395.png)

Below are the lines which are possibly relevant, but let me know if you need more of my .vimrc

```
" Set filetypes for unknown extensions
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd BufNewFile,BufReadPost *.apib set filetype=apiblueprint

" Syntastic
" ----------------------
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']
let g:syntastic_html_tidy_exec = 'tidy5' " use tidy-html5
```

**Comment by kylef** [comment]
Hi @benswinburne, could you confirm which version of `drafter` you have installed?

```shell
$ drafter --version
```
