### ISSUE TITLE
Don't remap <C-b> (default page-up)...

### ISSUE THREAD

**Issue by al-the-x** [kylef/apiblueprint.vim#16]
Thanks for the excellent work on this plugin, and while I appreciate the Syntastic integration and syntax highlighting, particularly when paired with [`aglio`](/danielgtaylor/aglio), mapping `<C-b>`, which is the default page-up command in `vim` was very surprising. Considering how often I hit `<C-b>` without thinking to jump up a page, it became down-right annoying. I edited the plugin file to map to `<Leader><C-b>` instead.

**Comment by kylef** [comment]
Hi @al-the-x,

I wasn't actually aware <C-b> went up in vim. I certainly agree the plugin should not override the default behaviour and will make this change.

**Comment by al-the-x** [comment]
No worries, sir. Thanks for your efforts! FWIW, check `:help CTRL-B` for that. It's a hold-over from `vi`, I believe, and also works in `less`, `more` et al. If you `:help maplocalleader`, you'll note that `vim` recommends plugins to map commands to `<Leader>`-prefixed commands... which almost no one respects, including @tpope (aka VIM PLUGIN MASTER)...!

**Comment by cweilemann** [comment]
@kylef thanks in advance - I've been banging my head against the wall for the past week. ;-)

**Comment by kylef** [comment]
I've updated this in 776b986 to no longer provide the mapping by default. Users can manually add the map if they wish.
