### ISSUE TITLE
underscore in MSON property name gets error highlighting

### ISSUE THREAD

**Issue by alextes** [kylef/apiblueprint.vim#17]
As far as I can tell from Apiary, drafter, and the MSON spec, having an underscore `_` in your property names is fine. Regardless in vim they light up like Christmas lights 🎄 !

![MSON with underscore property](https://cloud.githubusercontent.com/assets/2011351/21991898/aeebfb7c-dc14-11e6-9ec1-d20844c39085.png)

Love the plugin! Thank you.

**Comment by kylef** [comment]
The parameter name should be escaped via backticks (check out the note in MSON specification regarding reserved characters: https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords). drafter does support some cases of non-escaped fine, however you will see problems where you have multiple underscores for example the following:

```apib
+ Parameters
    + my_name: test - This description contains an underscore_.
```

Would be rendered in Apiary with the parameter name:

```
my_name: test - This description contains an underscore_.
```

**Comment by alextes** [comment]
Hah, all the way at the bottom. Hadn't seen that (only a note about escaping values) nor the catastrophic problem that results from trying to add italics later in the line.

Thanks for saving me from an error. Strange neither Apiary or drafter flags the unescaped property.

Cheers!

**Comment by alextes** [comment]
@kylef actually found an exception I think.
See: [uri-template-variable](https://apiblueprint.org/documentation/specification.html#uri-template-variable). I wouldn't care too much was it not that at least apiary no longer recognizes the URI parameter when backticks are added.

To make things worse, since the parameter is escaped drafter starts outputting a warning:
```
warning: (8)  parameter '`hub_id`' is not found within the URI template '/hubs/{hub_id}' for 'Hub'  :870:42
```

Maybe I should take this upstream?

**Comment by kylef** [comment]
That's a known issue (https://github.com/apiaryio/drafter/issues/445), we've made a fix and should be releasing it shortly (and subsequently deploying it to Apiary).

**Comment by alextes** [comment]
Subscribed. Thank you. Also, may I say holy-organisation-madness. I see you know the Apiary folks all too well. Thanks again!

**Comment by vassilevsky** [comment]
Making `_` a special symbol that requires backticking property names is the strangest decision ever. It is so common in all APIs.

**Comment by kylef** [comment]
`_` has other meaning in Markdown: `_italics_` (_italics_). While in some cases you can actually use `_` without escaping, if there is another `_` it can cause the area to become italics which can break other seperators (for example if `:` to separate key and value is inside an italics block).

Given the following:

<img width="377" alt="Screenshot 2019-05-24 at 08 53 02" src="https://user-images.githubusercontent.com/44164/58336709-784ead80-7e01-11e9-840b-96ecf0c37ded.png">
